package view;

import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import javax.swing.DefaultListModel;
import model.Agente;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author dam2_alu08@inf.ald
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private static DefaultListModel modeloAgentes = new DefaultListModel();

    public MainFrame() throws FileNotFoundException {
        initComponents();
        panelGrafico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanasTabbedPane = new javax.swing.JTabbedPane();
        graficaPanel = new javax.swing.JPanel();
        agentesPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        agenteList = new javax.swing.JList<>();
        usuarioTextField = new javax.swing.JTextField();
        saldoSpinner = new javax.swing.JSpinner();
        usuarioLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        addAgenteButton = new javax.swing.JButton();
        operacionesPanel = new javax.swing.JPanel();
        agentesComboBox = new javax.swing.JComboBox<>();
        agenteLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        precioLabel = new javax.swing.JLabel();
        precioSpinner = new javax.swing.JSpinner();
        cantidadLabel = new javax.swing.JLabel();
        cantidadSpinner = new javax.swing.JSpinner();
        saveButton = new javax.swing.JButton();
        compraLabel = new javax.swing.JLabel();
        ventaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graficaPanelLayout = new javax.swing.GroupLayout(graficaPanel);
        graficaPanel.setLayout(graficaPanelLayout);
        graficaPanelLayout.setHorizontalGroup(
            graficaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        graficaPanelLayout.setVerticalGroup(
            graficaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        ventanasTabbedPane.addTab("Grafica", graficaPanel);

        jScrollPane.setViewportView(agenteList);

        usuarioTextField.setText("");

        usuarioLabel.setText("Usuario");

        saldoLabel.setText("Saldo");

        addAgenteButton.setText("Añadir agente");

        javax.swing.GroupLayout agentesPanelLayout = new javax.swing.GroupLayout(agentesPanel);
        agentesPanel.setLayout(agentesPanelLayout);
        agentesPanelLayout.setHorizontalGroup(
            agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentesPanelLayout.createSequentialGroup()
                .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agentesPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(usuarioLabel))
                            .addGroup(agentesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(saldoLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(saldoSpinner)))
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addComponent(addAgenteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        agentesPanelLayout.setVerticalGroup(
            agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentesPanelLayout.createSequentialGroup()
                .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioLabel))
                        .addGap(29, 29, 29)
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saldoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(addAgenteButton))
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane)))
                .addContainerGap())
        );

        ventanasTabbedPane.addTab("Agentes", agentesPanel);

        agenteLabel.setText("Agente: ");

        typeLabel.setText("Tipo:");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona una opcion--", "Compra", "Venta" }));

        precioLabel.setText("Introduce el precio:");

        cantidadLabel.setText("Introduce la cantidad:");

        saveButton.setText("Guardar");

        compraLabel.setText("");

        ventaLabel.setText("");

        javax.swing.GroupLayout operacionesPanelLayout = new javax.swing.GroupLayout(operacionesPanel);
        operacionesPanel.setLayout(operacionesPanelLayout);
        operacionesPanelLayout.setHorizontalGroup(
            operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesPanelLayout.createSequentialGroup()
                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operacionesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(operacionesPanelLayout.createSequentialGroup()
                                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agenteLabel)
                                    .addComponent(typeLabel)
                                    .addComponent(precioLabel))
                                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(operacionesPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(agentesComboBox, 0, 608, Short.MAX_VALUE)
                                            .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(operacionesPanelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(precioSpinner))))
                            .addGroup(operacionesPanelLayout.createSequentialGroup()
                                .addComponent(cantidadLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadSpinner))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operacionesPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveButton))))
                    .addGroup(operacionesPanelLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ventaLabel)
                            .addComponent(compraLabel))
                        .addGap(0, 341, Short.MAX_VALUE)))
                .addContainerGap())
        );
        operacionesPanelLayout.setVerticalGroup(
            operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agentesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agenteLabel))
                .addGap(18, 18, 18)
                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel)
                    .addComponent(precioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadLabel)
                    .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(compraLabel)
                .addGap(18, 18, 18)
                .addComponent(ventaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        ventanasTabbedPane.addTab("Operaciones", operacionesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanasTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanasTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAgenteButtonActionListener(ActionListener al) {
        this.addAgenteButton.addActionListener(al);
    }

    public void panelGrafico() throws FileNotFoundException {
        Grafico grafico = new Grafico();
        ChartPanel panel = grafico.crearChartPanel();
        graficaPanel.setLayout(new java.awt.BorderLayout());
        graficaPanel.removeAll();
        graficaPanel.add(panel, java.awt.BorderLayout.CENTER);
        graficaPanel.revalidate();
        this.graficaPanel.repaint();
    }

    public void addSaveButtonActionListener(ActionListener al) {
        this.saveButton.addActionListener(al);
    }

    public void statusSaveButton(boolean bol) {
        this.saveButton.setEnabled(bol);
    }

    public void statusSpinners(boolean bol) {
        this.precioLabel.setVisible(bol);
        this.precioSpinner.setVisible(bol);
        this.cantidadSpinner.setVisible(bol);
        this.cantidadLabel.setVisible(bol);
    }

    public String getCantidadSpinnerValeu() {
        return this.cantidadSpinner.getValue().toString();
    }

    public String getPrecioSpinnerValue() {
        return this.precioSpinner.getValue().toString();
    }

    public void addItemComboBox(String item) {
        this.agentesComboBox.addItem(item);
    }

    public String getAgentesComboBoxContent() {
        return this.agentesComboBox.getItemAt(agentesComboBox.getSelectedIndex());
    }

    public String getTipoComboBoxContent() {
        return this.tipoComboBox.getItemAt(tipoComboBox.getSelectedIndex());
    }

    public int getTipoComboBoxSelection() {
        return this.tipoComboBox.getSelectedIndex();
    }

    public String getTextUsuarioTextField() {
        return this.usuarioTextField.getText();
    }

    public String getSaldoSpinner() {
        return this.saldoSpinner.getValue().toString();
    }

    public void addListItemAgente(Agente agente) {
        modeloAgentes.addElement(agente.toString());
        this.agenteList.setModel(modeloAgentes);
    }

    public int getVentanaTabbedPane() {
        if (this.ventanasTabbedPane.getSelectedIndex() < 0) {
        }
        return this.ventanasTabbedPane.getSelectedIndex();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAgenteButton;
    private javax.swing.JLabel agenteLabel;
    private javax.swing.JList<String> agenteList;
    private javax.swing.JComboBox<String> agentesComboBox;
    private javax.swing.JPanel agentesPanel;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JLabel compraLabel;
    private javax.swing.JPanel graficaPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel operacionesPanel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JSpinner precioSpinner;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JSpinner saldoSpinner;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioTextField;
    private javax.swing.JLabel ventaLabel;
    private javax.swing.JTabbedPane ventanasTabbedPane;
    // End of variables declaration//GEN-END:variables
}
