package view;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author dam2_alu08@inf.ald
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        graficaPanel = new javax.swing.JPanel();
        agentesPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        agenteList = new javax.swing.JList<>();
        usuarioTextField = new javax.swing.JTextField();
        saldoSpinner = new javax.swing.JSpinner();
        usuarioLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        addAgenteButton = new javax.swing.JButton();
        operacionesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graficaPanelLayout = new javax.swing.GroupLayout(graficaPanel);
        graficaPanel.setLayout(graficaPanelLayout);
        graficaPanelLayout.setHorizontalGroup(
            graficaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        graficaPanelLayout.setVerticalGroup(
            graficaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Grafica", graficaPanel);

        jScrollPane.setViewportView(agenteList);

        usuarioTextField.setText("");

        usuarioLabel.setText("Usuario");

        saldoLabel.setText("Saldo");

        addAgenteButton.setText("Añadir agente");

        javax.swing.GroupLayout agentesPanelLayout = new javax.swing.GroupLayout(agentesPanel);
        agentesPanel.setLayout(agentesPanelLayout);
        agentesPanelLayout.setHorizontalGroup(
            agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentesPanelLayout.createSequentialGroup()
                .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agentesPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(usuarioLabel))
                            .addGroup(agentesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(saldoLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(saldoSpinner)))
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addComponent(addAgenteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        agentesPanelLayout.setVerticalGroup(
            agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentesPanelLayout.createSequentialGroup()
                .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioLabel))
                        .addGap(29, 29, 29)
                        .addGroup(agentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saldoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addComponent(addAgenteButton))
                    .addGroup(agentesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane)))
                .addContainerGap())
        );

        jTabbedPane.addTab("Agentes", agentesPanel);

        javax.swing.GroupLayout operacionesPanelLayout = new javax.swing.GroupLayout(operacionesPanel);
        operacionesPanel.setLayout(operacionesPanelLayout);
        operacionesPanelLayout.setHorizontalGroup(
            operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        operacionesPanelLayout.setVerticalGroup(
            operacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Operaciones", operacionesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAgenteButtonActionListener(ActionListener al){
        this.addAgenteButton.addActionListener(al);
    }
    
    public String getTextUsuarioTextField(){
        return this.usuarioTextField.getText();
    }
    
    public String getSaldoSpinner(){
        return this.saldoSpinner.getValue().toString();
    }
    
    public void addListItem(String nombre, double saldo){
        DefaultListModel modelo = new DefaultListModel();
        modelo.addElement(nombre + " " + saldo);
        this.agenteList.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAgenteButton;
    private javax.swing.JList<String> agenteList;
    private javax.swing.JPanel agentesPanel;
    private javax.swing.JPanel graficaPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel operacionesPanel;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JSpinner saldoSpinner;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
